version: '3.1'

services:
    mail:
        image: maildev/maildev:latest
        restart: unless-stopped
        ports:
            - 1025:25
            - 1080:80
    
    alertmanager:
        image: prom/alertmanager:v0.21.0
        ports:
            - 9093:9093
        volumes:
            - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
            - ./alertmanager:/alertmanager:z
        restart: always
        command:
            - '--web.external-url=http://localhost:9093/'
            - '--cluster.listen-address='
            - '--config.file=/etc/alertmanager/alertmanager.yml'
            - '--storage.path=/alertmanager'
